<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.1.0</Version>
    <Product>DTM Toolbox for BLE</Product>
    <AssemblyTitle>DTM Toolbox for BLE</AssemblyTitle>
    <Description>Bluetooth LE Direct Test Mode over 2-wire UART</Description>
    <Authors>Felipe Dantas da Silva</Authors>
    <Company>Felipe Dantas da Silva</Company>
    <Copyright>Copyright (c) 2026 Felipe Dantas da Silva</Copyright>
    <RepositoryUrl>https://github.com/felipedts/dtm-toolbox-for-ble</RepositoryUrl>
  </PropertyGroup>

</Project>
